/**
 * Home page - Basic chat interface
 *
 * Displays ChatInterface with a default session.
 * Full UI with sidebar will be added in later user stories.
 *
 * @see tests/e2e/chat-input.spec.ts for E2E tests
 */

"use client";

import { ChatInterface } from "@/components/chat/ChatInterface";

export default function Home() {
  // Session ID will be generated by the SDK on first message
  // and captured from the init event
  const sessionId = undefined;

  return (
    <main className="flex h-screen flex-col">
      {/* Simple header */}
      <div className="border-b border-gray-300 bg-white px-20 py-16">
        <h1 className="text-16 font-semibold">Claude Agent Web</h1>
      </div>

      {/* Chat interface */}
      <ChatInterface sessionId={sessionId} />
    </main>
  );
}
